Blog App - Views
Bhekisile/blog-app pull request #6
Opened 2023-11-01 12:26 UTC by Bhekisile

## Changes

- Implemented list method on the controller

2023-11-01 17:29 UTC, aamirkhan2478 requested changes
Hi @Bhekisile, 

![](https://media2.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif?cid=ecf05e47k5uapdptg00nidbw3qaxx8iqgsusgaswci2c3uh1&rid=giphy.gif&ct=g)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Good Effort

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

[OPTIONAL] Please write a descriptive PR summary that mentions everything you did with that specific PR, so kindly change your PR summary.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-01 17:29 UTC, aamirkhan2478 commented on app/views/posts/index.html.erb
> +    </div>
- [ ] Please fix the following error I think you created your user's table with `user_id` but you passed `comment.author.name` instead of  `comment.user.name`  because if you the below error you will see the `undefined method 'author'` so kindly fix this error

![Screenshot from 2023-11-01 22-06-57](https://github.com/Bhekisile/blog-app/assets/45226848/eefedb6a-d6de-4353-8fdc-f1756e4f1ff5)

- [ ] I noticed you created your likes and comments tables with the foreign key `user_id` and created a posts table with `author_id` foreign key so kindly replace your all `user_id` with `author_id` foreign keys after that you don't need to replace `comment.user.name` with `comment.author.name` as I mentioned above :slightly_smiling_face: 

![Screenshot from 2023-11-01 22-13-48](https://github.com/Bhekisile/blog-app/assets/45226848/fe95edc5-9c0e-4cd2-9afd-c4646daae9e2)

2023-11-01 21:40 UTC, zieeco requested changes
Hi @Bhekisile,


<img height="80" src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>



Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the changes, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- Great effort making the requested changes ✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._




## Optional suggestions

- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-01 21:40 UTC, zieeco commented on db/migrate/20231024032549_create_comments.rb
> +      t.references :author, foreign_key: true
- Hey, while you've made the change as suggested, however, you should leave it a `user` instead of `author` in this case as it throws an error of  ` ERROR:  relation "authors" does not exist`.

2023-11-01 21:40 UTC, zieeco commented on db/migrate/20231024032905_create_likes.rb
> +      t.references :author, foreign_key: true
- Hey, while you've made the change as suggested, however, you should leave it a `user` instead of `author` in this case as it throws an error of  ` ERROR:  relation "authors" does not exist`. 

*After you make these changes I suggest, run your migration and your app will work fine and as expected*

2023-11-02 08:14 UTC, topeogunleye approved these changes
### Hi @Bhekisile, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 

- 🎉 Great job implementing the requested changes!
- 🚀 I appreciate your attention to detail and responsiveness to feedback.
- ✅ It's great to see that the issue with the `ERROR: relation "authors" does not exist` has been addressed.
- 💡 Always make sure to run tests after any modifications to confirm everything works as expected.

Keep it up! You're doing fantastic! 🌼
## [Optional] suggestions:
- For future pull requests, please notice that your branch name `views` does not follow the convention of being named after a feature or action. For example, you could name your branch `added-views`. This makes it easier to track the changes and the purpose of each branch. 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-02 10:14 UTC, merged