Integration specs for views and fix n+1 problems
Bhekisile/blog-app pull request #9
Opened 2023-11-06 12:32 UTC by Bhekisile

## Changes

- Added capybara driver and application system test case
-

2023-11-07 11:22 UTC, Reem-lab requested changes
# Hi @Bhekisile and @M-AminAlizadeh, 👋🏻👋🏻 

Great job so far! 🔥✨💯⭐
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights

- [ ] No Linters error 🚀
- [ ] Followed GitFlow 💯
- [ ] Great for adding the view tests👏🏻
- [ ] Descriptive PR 💯
- [ ] Amazing for solving n+1 problem with adding the screenshots 🚀

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-07 11:22 UTC, Reem-lab commented on spec/system/user_post_index_spec.rb
> +    # end
- [ ] Great job working on the tests so far but I think it would be great if you removed the commented code from your codebase since commented-out code is a huge problem. Unlike normal comments, they aren't meant to clarify anything. Instead, they add clutter to the code that can only increase confusion. so kindly remove it to make our code base clean dry and KISS 💯🔥✨✅

2023-11-07 11:22 UTC, Reem-lab commented on spec/system/user_post_index_spec.rb
> +
- [ ] Great job working on the tests so far but I think it would be great if you add Tests that asserts you can see how many likes a post has. since I couldn't tests for that here so kindly add it ✅✨🔥

2023-11-07 11:22 UTC, Reem-lab commented on spec/system/user_show_spec.rb
> +  end
- [ ] Great job for adding * Tests that redirects to the user's post's index page when you click on a **see all posts**. but I think you forget to add add Tests that redirects to the post's show page when you click on a user's post. and I think you combined them here in one test so it would be great if you add test for each feature as mentioned in the requirements 🔥⭐💪🏻


![image](https://github.com/Bhekisile/blog-app/assets/58553711/88522d1c-a161-4864-92a2-fb03662061ef)

2023-11-07 15:02 UTC, Bhekisile commented on spec/system/user_post_index_spec.rb
> +    # end
Fixed, thank you.

2023-11-07 15:02 UTC, Bhekisile commented on spec/system/user_post_index_spec.rb
> +
Fixed, thank you.

2023-11-07 15:02 UTC, Bhekisile commented on spec/system/user_show_spec.rb
> +  end
Fixed, thank you.

2023-11-07 16:35 UTC, zieeco requested changes
Hi @Team,

<img height="80" src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>



Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the changes, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- Implemented some requested changes ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


## Optional suggestions

- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-07 16:35 UTC, zieeco commented on spec/system/user_index_spec.rb
> +    end
- Great job adding the test as suggested by the previous reviewer, however, the test fails to pass. please, reevaluate the test as seen below to improve it .

![image](https://github.com/Bhekisile/blog-app/assets/59397159/97bb0018-0618-4636-9a10-8d2a394878ad)

2023-11-07 19:50 UTC, Bhekisile commented on spec/system/user_index_spec.rb
> +    end
Thank  you for the feedback. I have checked and double checked, I've run my test several times and it passed so I don't think the error is coming from my end. Below is a screenshot of my test.

![image](https://github.com/Bhekisile/blog-app/assets/111288560/168fe06c-8a00-4c02-a96b-f756daf18792)

2023-11-07 20:45 UTC, FrederickMih requested changes
## Hi :raising_hand: :raising_hand: @Bhekisile, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Highlights :green_circle: 

- Some unit tests runs with success :+1: 



 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-07 20:45 UTC, FrederickMih commented on spec/system/user_index_spec.rb
> +    end
- [ ] Hi @Bhekisile, I'm sorry to let you know that this test is not also running at my end  You can see hints about the error on the console below: 
![Screenshot from 2023-11-07 21-27-13](https://github.com/Bhekisile/blog-app/assets/63087491/f2a5fc36-4b97-4a48-bca7-5afae90d43c0)

- I think the error arises due to the way you are finding the user. All the other tests are running perfectly apart from this one hence I think  the error is not at our end. Kindly double-check once more.

2023-11-07 20:45 UTC, FrederickMih commented on spec/system/user_index_spec.rb
> +    it "When I click on a user, I am redirected to that user's show page." do
- [Optional] The statement in "it" block is not really clear enough as you can see on the screenshot below. Let's try to rephrase all blocks phrases to make the final hypothesis statement clear. It is also great to use only a single "describe" block and make use of "context" blocks instead :+1: 
![Screenshot from 2023-11-07 21-40-39](https://github.com/Bhekisile/blog-app/assets/63087491/dd3dd9a9-678a-424c-a011-f940f87412a5)

2023-11-08 09:25 UTC, Bhekisile commented on spec/system/user_index_spec.rb
> +    end
I really don't understand the problem but I have used database cleaner because as I googled the problem someone said this might happen when the database test is not releasing old data. I hope it will work this time.
Thank you

2023-11-08 10:10 UTC, uwadonat approved these changes
## Hi @Bhekisile ,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 
- Correct workflow was used ✔️
- Well-organized and clean project ✔️
- No linter error ✔️
- Professional readme file ✔️
![approv](https://github.com/hetrox8/Blog_App/assets/65860678/80ab9621-2395-468f-b148-b3222ba1a2ab)

# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-11-08 10:13 UTC, merged